isDevelopment: true
addr: :8080
uiProxy: ""
siteName: Discuit
siteDescription: A free and open-source community platform.
dbAddr: 127.0.0.1
dbUser: discuit
dbPassword: discuit
dbName: discuit
sessionCookieName: SID
redisAddress: :6379
hmacSecret: 7f3a9b2c1e8d4f6a0e5d2c7b9a3f1e8d
csrfOff: false
noLogToFile: false
paginationLimit: 10
paginationLimitMax: 50
defaultFeedSort: hot
captchaSecret: ""
certFile: ""
keyFile: ""
disableRateLimits: false
maxImageSize: 26214400
adminAPIKey: ""
disableImagePosts: false
disableForumCreation: true
forumCreationReqPoints: 10
maxForumsPerUser: 10
imagesFolderPath: images
maxImagesPerPost: 10
captchaSiteKey: ""
emailContact: ""
facebookURL: ""
twitterURL: ""
instagramURL: ""
discordURL: ""
githubURL: https://github.com/discuitnet/discuit
substackURL: ""

